### ISSUE TITLE
PDF Sandwich action for nemo throws blank page with scantailor-advanced

### ISSUE THREAD

**Issue by SoulInfernoDE** [Alfcx/linux-mint-nemo-actions#3]
Hi @Alfcx ,
i like your handy tools to create a cool scan workflow.
I am using them to digitalize all my documents.

There is a problem with the pdf sandwich action. Since scantailor is not
updated anymore i am using scantailor-advanced. And there seems to be no
accessible scantailor-cli. Instead i tried to replace the requirement to
scantailor-advanced in your files. But guess what i get an successfully converted message
with a blank white page as end result.
Seems that there needs to be some updates for scantailor-advanced for the command line
arguments i guess. Could you investigate?

with best regards

Soul Inferno

**Comment by Alfcx** [comment]
Hi @SoulInfernoDE 

Sounds like scantailor-advanced uses different cli-arguments (which should be easy to adapt).
Im not able to investigate because I still use scantailor (on debian buster) for the most stable results

Best regards

Alfcx

**Comment by SoulInfernoDE** [comment]
Hi, oh that's confusing I thought you wrote it's for nemo with linux mint which I am using atm. I didn't knew you did switch to Debian? best regards Si-Am 31.08.21, 17:22 schrieb Alfcx ***@***.***>:

   
  Hi @SoulInfernoDE 
  Sounds like scantailor-advanced uses different cli-arguments (which should be easy to adapt). Im not able to investigate because I still use scantailor (on debian buster) for the most stable results 
  Best regards 
  Alfcx
